CC=gcc
CFLAGS=-Wall -Werror

all:b b.exe  # 想要从生成的文件必须写在all 后面

b: b.c
	$(CC) -o b b.c

b.exe:b.c
	$(CC) -o b.exe b.c
	

#CC=gcc
#CFLAGS=-Wall -Werror


# clean:
#	rm -f testSubsetList subsetList.o testSubsetList.o core

